version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 10
    groups:
      javascript:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: /services/api
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 10
    groups:
      java:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /infra/local
    schedule:
      interval: weekly
      day: monday
      time: "03:45"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
